Add DeleteWrapperProxyHandler
servo/mozjs pull request #470
Opened 2024-07-01 21:16 UTC by ede1998

This function is needed to be able to release the memory allocated by CreateWrapperProxyHandler from Rust after use.

This came up while investigating memory leaks in servo (servo/servo#32223). With this function added, we managed to create a proof of concept to fix the leak.

CC @rhetenor

2024-07-01 21:58 UTC, jdm approved these changes

2024-07-01 21:59 UTC, jdm reviewed
I think you need to add Rust bindings for the new function in glue.rs in the mozjs crate as well.

2024-07-01 22:01 UTC, jdm commented
Mmm, nevermind the last comment. I've forgotten the details of how the various pieces are autogenerated.

2024-07-02 04:02 UTC, sagudev requested changes
Needs rebase and bumping version of mozjs-sys, see https://github.com/servo/mozjs/pull/456#issue-2172138365 for details.

2024-07-02 08:18 UTC, sagudev approved these changes

2024-07-02 08:39 UTC, merged