Fix mmap for JIT code on HarmonyOS NEXT Beta 2
servo/mozjs pull request #491
Opened 2024-08-05 07:07 UTC by jschwe

The Security policy for JIT code is tightening and Beta 2 and newer require us to pass `MAP_EXECUTABLE` (internally same as `MAP_JIT`) to the committing mmap, otherwise it will fail.

2024-08-05 11:18 UTC, Taym95 commented on mozjs-sys/etc/patches/0034-build__Add_compile_definition_for_ohos.patch
> ++    if target.raw_os.endswith("-ohos"):
```suggestion
+    return target.raw_os.endswith("-ohos"):
```
?

2024-08-05 11:20 UTC, Taym95 commented on mozjs-sys/etc/patches/0034-build__Add_compile_definition_for_ohos.patch
> ++    log.info(f"target {target}")
log still needed?

2024-08-05 11:29 UTC, jschwe commented on mozjs-sys/etc/patches/0034-build__Add_compile_definition_for_ohos.patch
> ++    log.info(f"target {target}")
No. Thanks for catching :).

2024-08-05 13:09 UTC, sagudev requested changes
I think we need to bump mozjs-sys version for this and it would be nice to add ohos in CI (like it is in servo), so we can land with more confidence that it compiles (ideally in separate PR).

2024-08-05 13:41 UTC, jschwe commented
> it would be nice to add ohos in CI 

Sure, I'll open a separate PR for that as suggested.

2024-08-06 11:30 UTC, sagudev approved these changes

2024-08-06 11:55 UTC, merged